pipeline {
  agent {
    node {
      label 'docker-agent-python'
    }      
  }
    stages {
        stage('Checkout') {
             steps {
               sh 'ls -lrt'
              //git branch: 'main', url: 'https://github.com/Rutakara/Jenkins-ArgoCD-Project.git'
      
            }
        }
        stage ('Build') {
             steps {
              sh 'pip install requirements.txt'
             }
        }
    }
}
